-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 14:19:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dh_bikes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dh_bikes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dh_bikes` DEFAULT CHARACTER SET utf8mb4 ;
USE `dh_bikes` ;

-- -----------------------------------------------------
-- Table `dh_bikes`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dh_bikes`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`products` (
  `id_products` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_products`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `dh_bikes`.`category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dh_bikes`.`user_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`user_category` (
  `id_user_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 1002
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dh_bikes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`user` (
  `id` INT(11) NOT NULL,
  `id_user_category` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_category` (`id_user_category` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`id_user_category`)
    REFERENCES `dh_bikes`.`user_category` (`id_user_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dh_bikes`.`shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`shopping` (
  `id_shopping` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_shopping`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `shopping_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dh_bikes`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dh_bikes`.`products_shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_bikes`.`products_shopping` (
  `id_products_shopping` INT(11) NOT NULL AUTO_INCREMENT,
  `id_products` INT(11) NOT NULL,
  `id_shopping` INT(11) NOT NULL,
  PRIMARY KEY (`id_products_shopping`),
  INDEX `id_products` (`id_products` ASC) VISIBLE,
  INDEX `id_shopping` (`id_shopping` ASC) VISIBLE,
  CONSTRAINT `products_shopping_ibfk_1`
    FOREIGN KEY (`id_products`)
    REFERENCES `dh_bikes`.`products` (`id_products`),
  CONSTRAINT `products_shopping_ibfk_2`
    FOREIGN KEY (`id_shopping`)
    REFERENCES `dh_bikes`.`shopping` (`id_shopping`))
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
